models:
  LogoDetection:
    paths:
      model: "./stored_models/LogoDetection"
      train_cp: "./data/stored_models/checkpoints"

datasets:
  FlickrLogos-32:
      paths:
        images: "./data/dataset/FlickrLogos-v2/classes/jpg"
        masks: "./data/dataset/FlickrLogos-v2/classes/masks"
      bbox_suffix: ".bboxes.txt"
  FlickrLogos-32-test:
      paths:
        images: "./data/dataset/FlickrLogos-v2-test/classes/jpg"
        masks: "./data/dataset/FlickrLogos-v2-test/classes/masks"
      bbox_suffix: ".bboxes.txt"
  TopLogos-10:
      paths:
        images: "./data/dataset/qmul_toplogo10/jpg"
        masks: "./data/dataset/qmul_toplogo10/masks"
      bbox_suffix: ".bboxes.txt"
  TopLogos-10-Flickr-32-test:
      paths:
        images: "./data/dataset/FlickrLogos-v2-test/classes/jpg"
        masks: "./data/dataset/FlickrLogos-v2-test/classes/masks"
      bbox_suffix: ".bboxes.txt"
  FlickrLogos-20:
      paths:
        images: "./data/dataset/FlickrLogos-v2-20/classes/jpg"
        masks: "./data/dataset/FlickrLogos-v2-20/classes/masks"
      bbox_suffix: ".bboxes.txt"
  FlickrLogos-12:
      paths:
        images: "./data/dataset/FlickrLogos-v2-12/classes/jpg"
        masks: "./data/dataset/FlickrLogos-v2-12/classes/masks"
      bbox_suffix: ".bboxes.txt"
  TopLogos-10-Flickr-12-test:
      paths:
        images: "./data/dataset/FlickrLogos-v2-12/classes/jpg"
        masks: "./data/dataset/FlickrLogos-v2-12/classes/masks"
      bbox_suffix: ".bboxes.txt"
